import '../../money/currency.dart';
import '../../money/money.dart';
import '../../repositories/card_repository.dart';
import '../../repositories/employee_repository.dart';
import '../../repositories/payroll_repository.dart';
import '../../repositories/wallet_repository.dart';

/// Deterministic Demo Data
/// Incorporates official BMONI Sandbox personas & multi-country rails:
/// 1. Bunch Dillon (Nigeria, BVN 99999999999, NGN / CNGN)
/// 2. Samson Jabo (Mexico, BVN/NIN 22222222222, MXN / MEXe)
/// 3. Liam Tremblay (Canada, CAD / CADC)
class DemoData {
  static final List<WalletAccount> wallets = [
    WalletAccount(
      id: 'sw_demo_usdb_01',
      address: '0x8f2d6B48e89405d414a3D65B2Af6d73f1d93E3C1',
      currency: Currency.usd,
      stablecoinToken: 'USDB',
      balance: Money.fromMajorString('24500.00', Currency.usd),
      status: 'active',
    ),
    WalletAccount(
      id: 'sw_demo_cngn_02',
      address: '0x3A9a92C1897d2eB6C6a76C2Ef331908C5b38F242',
      currency: Currency.ngn,
      stablecoinToken: 'CNGN',
      balance: Money.fromMajorString('6820000.00', Currency.ngn),
      status: 'active',
    ),
    WalletAccount(
      id: 'sw_demo_mexe_03',
      address: '0x9B10d4818F2312643a60a7F03C12b07C6418B573',
      currency: Currency.mxn,
      stablecoinToken: 'MEXe',
      balance: Money.fromMajorString('48500.00', Currency.mxn),
      status: 'active',
    ),
    WalletAccount(
      id: 'sw_demo_cadc_04',
      address: '0x1C44F5a92B7e012354c41893D9B0A361e2A89F90',
      currency: Currency.cad,
      stablecoinToken: 'CADC',
      balance: Money.fromMajorString('8250.00', Currency.cad),
      status: 'active',
    ),
  ];

  static final List<EmployeeModel> employees = [
    EmployeeModel(
      id: 'emp_bunch_dillon',
      bmoniUserId: 'usr_bmoni_dillon_ngn',
      firstName: 'Bunch',
      lastName: 'Dillon',
      email: 'bunch.dillon@example.ng',
      phoneNumber: '+2348011112222',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('3100000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('2000.00', Currency.usd),
      walletAddress: '0xbunc...llon',
      cardId: 'card_demo_ngn_8814',
      cardLast4: '8814',
    ),
    EmployeeModel(
      id: 'emp_samson_jabo',
      bmoniUserId: 'usr_bmoni_samson_mxn',
      firstName: 'Samson',
      lastName: 'Jabo',
      email: 'samson.jabo@example.mx',
      phoneNumber: '+525512345678',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('35000.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('2000.00', Currency.usd),
      walletAddress: '0xsams...jabo',
      cardId: 'card_demo_mxn_4289',
      cardLast4: '4289',
    ),
    EmployeeModel(
      id: 'emp_liam_tremblay',
      bmoniUserId: 'usr_bmoni_liam_cad',
      firstName: 'Liam',
      lastName: 'Tremblay',
      email: 'liam.tremblay@example.ca',
      phoneNumber: '+14165550192',
      country: 'CA',
      countryName: 'Canada',
      targetCurrency: Currency.cad,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('4400.00', Currency.cad),
      usdPayrollAmount: Money.fromMajorString('3200.00', Currency.usd),
      walletAddress: '0xliam...blay',
      cardId: 'card_demo_cad_9032',
      cardLast4: '9032',
    ),
    EmployeeModel(
      id: 'emp_chioma_okafor',
      bmoniUserId: 'usr_bmoni_chioma_ngn',
      firstName: 'Chioma',
      lastName: 'Okafor',
      email: 'chioma.okafor@example.ng',
      phoneNumber: '+2348022223333',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('3875000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('2500.00', Currency.usd),
      walletAddress: '0xchio...afor',
      cardId: 'card_demo_ngn_7721',
      cardLast4: '7721',
    ),
    EmployeeModel(
      id: 'emp_mateo_hernandez',
      bmoniUserId: 'usr_bmoni_mateo_mxn',
      firstName: 'Mateo',
      lastName: 'Hernandez',
      email: 'mateo.hernandez@example.mx',
      phoneNumber: '+525523456789',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('38500.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('2200.00', Currency.usd),
      walletAddress: '0xmate...ndez',
      cardId: 'card_demo_mxn_6612',
      cardLast4: '6612',
    ),
    EmployeeModel(
      id: 'emp_babatunde_adeyemi',
      bmoniUserId: 'usr_bmoni_babatunde_ngn',
      firstName: 'Babatunde',
      lastName: 'Adeyemi',
      email: 'babatunde.adeyemi@example.ng',
      phoneNumber: '+2348033334444',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('4650000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('3000.00', Currency.usd),
      walletAddress: '0xbaba...yemi',
      cardId: 'card_demo_ngn_5543',
      cardLast4: '5543',
    ),
    EmployeeModel(
      id: 'emp_sofia_rodriguez',
      bmoniUserId: 'usr_bmoni_sofia_mxn',
      firstName: 'Sofia',
      lastName: 'Rodriguez',
      email: 'sofia.rodriguez@example.mx',
      phoneNumber: '+525534567890',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('49000.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('2800.00', Currency.usd),
      walletAddress: '0xsofi...guez',
      cardId: 'card_demo_mxn_4432',
      cardLast4: '4432',
    ),
    EmployeeModel(
      id: 'emp_emma_roy',
      bmoniUserId: 'usr_bmoni_emma_cad',
      firstName: 'Emma',
      lastName: 'Roy',
      email: 'emma.roy@example.ca',
      phoneNumber: '+15145550183',
      country: 'CA',
      countryName: 'Canada',
      targetCurrency: Currency.cad,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('3987.50', Currency.cad),
      usdPayrollAmount: Money.fromMajorString('2900.00', Currency.usd),
      walletAddress: '0xemma..._roy',
      cardId: 'card_demo_cad_3321',
      cardLast4: '3321',
    ),
    EmployeeModel(
      id: 'emp_ngozi_eze',
      bmoniUserId: 'usr_bmoni_ngozi_ngn',
      firstName: 'Ngozi',
      lastName: 'Eze',
      email: 'ngozi.eze@example.ng',
      phoneNumber: '+2348044445555',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('3255000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('2100.00', Currency.usd),
      walletAddress: '0xngoz..._eze',
      cardId: 'card_demo_ngn_2210',
      cardLast4: '2210',
    ),
    EmployeeModel(
      id: 'emp_carlos_gonzalez',
      bmoniUserId: 'usr_bmoni_carlos_mxn',
      firstName: 'Carlos',
      lastName: 'Gonzalez',
      email: 'carlos.gonzalez@example.mx',
      phoneNumber: '+525545678901',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('42000.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('2400.00', Currency.usd),
      walletAddress: '0xcarl...alez',
      cardId: 'card_demo_mxn_1109',
      cardLast4: '1109',
    ),
    EmployeeModel(
      id: 'emp_olumide_bakare',
      bmoniUserId: 'usr_bmoni_olumide_ngn',
      firstName: 'Olumide',
      lastName: 'Bakare',
      email: 'olumide.bakare@example.ng',
      phoneNumber: '+2348055556666',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('5425000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('3500.00', Currency.usd),
      walletAddress: '0xolum...kare',
      cardId: 'card_demo_ngn_9988',
      cardLast4: '9988',
    ),
    EmployeeModel(
      id: 'emp_valentina_morales',
      bmoniUserId: 'usr_bmoni_valentina_mxn',
      firstName: 'Valentina',
      lastName: 'Morales',
      email: 'valentina.morales@example.mx',
      phoneNumber: '+525556789012',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('54250.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('3100.00', Currency.usd),
      walletAddress: '0xvale...ales',
      cardId: 'card_demo_mxn_8877',
      cardLast4: '8877',
    ),
    EmployeeModel(
      id: 'emp_noah_bouchard',
      bmoniUserId: 'usr_bmoni_noah_cad',
      firstName: 'Noah',
      lastName: 'Bouchard',
      email: 'noah.bouchard@example.ca',
      phoneNumber: '+14035550174',
      country: 'CA',
      countryName: 'Canada',
      targetCurrency: Currency.cad,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('4675.00', Currency.cad),
      usdPayrollAmount: Money.fromMajorString('3400.00', Currency.usd),
      walletAddress: '0xnoah...hard',
      cardId: 'card_demo_cad_7766',
      cardLast4: '7766',
    ),
    EmployeeModel(
      id: 'emp_amina_bello',
      bmoniUserId: 'usr_bmoni_amina_ngn',
      firstName: 'Amina',
      lastName: 'Bello',
      email: 'amina.bello@example.ng',
      phoneNumber: '+2348066667777',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('3410000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('2200.00', Currency.usd),
      walletAddress: '0xamin...ello',
      cardId: 'card_demo_ngn_6655',
      cardLast4: '6655',
    ),
    EmployeeModel(
      id: 'emp_diego_perez',
      bmoniUserId: 'usr_bmoni_diego_mxn',
      firstName: 'Diego',
      lastName: 'Perez',
      email: 'diego.perez@example.mx',
      phoneNumber: '+525567890123',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('45500.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('2600.00', Currency.usd),
      walletAddress: '0xdieg...erez',
      cardId: 'card_demo_mxn_5544',
      cardLast4: '5544',
    ),
    EmployeeModel(
      id: 'emp_chukwudi_nwosu',
      bmoniUserId: 'usr_bmoni_chukwudi_ngn',
      firstName: 'Chukwudi',
      lastName: 'Nwosu',
      email: 'chukwudi.nwosu@example.ng',
      phoneNumber: '+2348077778888',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('4340000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('2800.00', Currency.usd),
      walletAddress: '0xchuk...wosu',
      cardId: 'card_demo_ngn_4433',
      cardLast4: '4433',
    ),
    EmployeeModel(
      id: 'emp_isabella_sanchez',
      bmoniUserId: 'usr_bmoni_isabella_mxn',
      firstName: 'Isabella',
      lastName: 'Sanchez',
      email: 'isabella.sanchez@example.mx',
      phoneNumber: '+525578901234',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('57750.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('3300.00', Currency.usd),
      walletAddress: '0xisab...chez',
      cardId: 'card_demo_mxn_3322',
      cardLast4: '3322',
    ),
    EmployeeModel(
      id: 'emp_olivia_gauthier',
      bmoniUserId: 'usr_bmoni_olivia_cad',
      firstName: 'Olivia',
      lastName: 'Gauthier',
      email: 'olivia.gauthier@example.ca',
      phoneNumber: '+16045550165',
      country: 'CA',
      countryName: 'Canada',
      targetCurrency: Currency.cad,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('4125.00', Currency.cad),
      usdPayrollAmount: Money.fromMajorString('3000.00', Currency.usd),
      walletAddress: '0xoliv...hier',
      cardId: 'card_demo_cad_2211',
      cardLast4: '2211',
    ),
    EmployeeModel(
      id: 'emp_yetunde_adeleke',
      bmoniUserId: 'usr_bmoni_yetunde_ngn',
      firstName: 'Yetunde',
      lastName: 'Adeleke',
      email: 'yetunde.adeleke@example.ng',
      phoneNumber: '+2348088889999',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('3720000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('2400.00', Currency.usd),
      walletAddress: '0xyetu...leke',
      cardId: 'card_demo_ngn_1199',
      cardLast4: '1199',
    ),
    EmployeeModel(
      id: 'emp_emiliano_ramirez',
      bmoniUserId: 'usr_bmoni_emiliano_mxn',
      firstName: 'Emiliano',
      lastName: 'Ramirez',
      email: 'emiliano.ramirez@example.mx',
      phoneNumber: '+525589012345',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('47250.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('2700.00', Currency.usd),
      walletAddress: '0xemil...irez',
      cardId: 'card_demo_mxn_9977',
      cardLast4: '9977',
    ),
    EmployeeModel(
      id: 'emp_femi_ojo',
      bmoniUserId: 'usr_bmoni_femi_ngn',
      firstName: 'Femi',
      lastName: 'Ojo',
      email: 'femi.ojo@example.ng',
      phoneNumber: '+2348099990000',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('3565000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('2300.00', Currency.usd),
      walletAddress: '0xfemi..._ojo',
      cardId: 'card_demo_ngn_8866',
      cardLast4: '8866',
    ),
    EmployeeModel(
      id: 'emp_camila_flores',
      bmoniUserId: 'usr_bmoni_camila_mxn',
      firstName: 'Camila',
      lastName: 'Flores',
      email: 'camila.flores@example.mx',
      phoneNumber: '+525590123456',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('43750.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('2500.00', Currency.usd),
      walletAddress: '0xcami...ores',
      cardId: 'card_demo_mxn_7755',
      cardLast4: '7755',
    ),
    EmployeeModel(
      id: 'emp_lucas_morin',
      bmoniUserId: 'usr_bmoni_lucas_cad',
      firstName: 'Lucas',
      lastName: 'Morin',
      email: 'lucas.morin@example.ca',
      phoneNumber: '+16135550156',
      country: 'CA',
      countryName: 'Canada',
      targetCurrency: Currency.cad,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('3850.00', Currency.cad),
      usdPayrollAmount: Money.fromMajorString('2800.00', Currency.usd),
      walletAddress: '0xluca...orin',
      cardId: 'card_demo_cad_6644',
      cardLast4: '6644',
    ),
    EmployeeModel(
      id: 'emp_zainab_aliyu',
      bmoniUserId: 'usr_bmoni_zainab_ngn',
      firstName: 'Zainab',
      lastName: 'Aliyu',
      email: 'zainab.aliyu@example.ng',
      phoneNumber: '+2348012345678',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('4030000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('2600.00', Currency.usd),
      walletAddress: '0xzain...liyu',
      cardId: 'card_demo_ngn_5533',
      cardLast4: '5533',
    ),
    EmployeeModel(
      id: 'emp_santiago_torres',
      bmoniUserId: 'usr_bmoni_santiago_mxn',
      firstName: 'Santiago',
      lastName: 'Torres',
      email: 'santiago.torres@example.mx',
      phoneNumber: '+525501234567',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('52500.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('3000.00', Currency.usd),
      walletAddress: '0xsant...rres',
      cardId: 'card_demo_mxn_4422',
      cardLast4: '4422',
    ),
    EmployeeModel(
      id: 'emp_emeka_okonkwo',
      bmoniUserId: 'usr_bmoni_emeka_ngn',
      firstName: 'Emeka',
      lastName: 'Okonkwo',
      email: 'emeka.okonkwo@example.ng',
      phoneNumber: '+2348023456789',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('4960000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('3200.00', Currency.usd),
      walletAddress: '0xemek...nkwo',
      cardId: 'card_demo_ngn_3311',
      cardLast4: '3311',
    ),
    EmployeeModel(
      id: 'emp_natalia_diaz',
      bmoniUserId: 'usr_bmoni_natalia_mxn',
      firstName: 'Natalia',
      lastName: 'Diaz',
      email: 'natalia.diaz@example.mx',
      phoneNumber: '+525512345670',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('50750.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('2900.00', Currency.usd),
      walletAddress: '0xnata...diaz',
      cardId: 'card_demo_mxn_2200',
      cardLast4: '2200',
    ),
    EmployeeModel(
      id: 'emp_charlotte_tremblay',
      bmoniUserId: 'usr_bmoni_charlotte_cad',
      firstName: 'Charlotte',
      lastName: 'Tremblay',
      email: 'charlotte.tremblay@example.ca',
      phoneNumber: '+19025550147',
      country: 'CA',
      countryName: 'Canada',
      targetCurrency: Currency.cad,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('4950.00', Currency.cad),
      usdPayrollAmount: Money.fromMajorString('3600.00', Currency.usd),
      walletAddress: '0xchar...blay',
      cardId: 'card_demo_cad_1188',
      cardLast4: '1188',
    ),
    EmployeeModel(
      id: 'emp_folake_thomas',
      bmoniUserId: 'usr_bmoni_folake_ngn',
      firstName: 'Folake',
      lastName: 'Thomas',
      email: 'folake.thomas@example.ng',
      phoneNumber: '+2348034567890',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('4185000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('2700.00', Currency.usd),
      walletAddress: '0xfola...omas',
      cardId: 'card_demo_ngn_9966',
      cardLast4: '9966',
    ),
    EmployeeModel(
      id: 'emp_leonardo_castillo',
      bmoniUserId: 'usr_bmoni_leonardo_mxn',
      firstName: 'Leonardo',
      lastName: 'Castillo',
      email: 'leonardo.castillo@example.mx',
      phoneNumber: '+525523456781',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'ACTIVE',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('56000.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('3200.00', Currency.usd),
      walletAddress: '0xleon...illo',
      cardId: 'card_demo_mxn_8855',
      cardLast4: '8855',
    ),
    EmployeeModel(
      id: 'emp_damilola_shittu',
      bmoniUserId: 'usr_bmoni_damilola_ngn',
      firstName: 'Damilola',
      lastName: 'Shittu',
      email: 'damilola.shittu@example.ng',
      phoneNumber: '+2348045678901',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'READY',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('3875000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('2500.00', Currency.usd),
      walletAddress: '0xdami...ittu',
      cardId: 'card_demo_ngn_7744',
      cardLast4: '7744',
    ),
    EmployeeModel(
      id: 'emp_valeria_vasquez',
      bmoniUserId: 'usr_bmoni_valeria_mxn',
      firstName: 'Valeria',
      lastName: 'Vasquez',
      email: 'valeria.vasquez@example.mx',
      phoneNumber: '+525534567892',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'READY',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('49000.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('2800.00', Currency.usd),
      walletAddress: '0xvale...quez',
      cardId: 'card_demo_mxn_6633',
      cardLast4: '6633',
    ),
    EmployeeModel(
      id: 'emp_benjamin_fortin',
      bmoniUserId: 'usr_bmoni_benjamin_cad',
      firstName: 'Benjamin',
      lastName: 'Fortin',
      email: 'benjamin.fortin@example.ca',
      phoneNumber: '+12045550138',
      country: 'CA',
      countryName: 'Canada',
      targetCurrency: Currency.cad,
      status: 'READY',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('4262.50', Currency.cad),
      usdPayrollAmount: Money.fromMajorString('3100.00', Currency.usd),
      walletAddress: '0xbenj...rtin',
      cardId: 'card_demo_cad_5522',
      cardLast4: '5522',
    ),
    EmployeeModel(
      id: 'emp_kelechi_ibe',
      bmoniUserId: 'usr_bmoni_kelechi_ngn',
      firstName: 'Kelechi',
      lastName: 'Ibe',
      email: 'kelechi.ibe@example.ng',
      phoneNumber: '+2348056789012',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'READY',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('4650000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('3000.00', Currency.usd),
      walletAddress: '0xkele..._ibe',
      cardId: 'card_demo_ngn_4411',
      cardLast4: '4411',
    ),
    EmployeeModel(
      id: 'emp_sebastian_ortiz',
      bmoniUserId: 'usr_bmoni_sebastian_mxn',
      firstName: 'Sebastian',
      lastName: 'Ortiz',
      email: 'sebastian.ortiz@example.mx',
      phoneNumber: '+525545678903',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'READY',
      onboardingStatus: 'ONBOARDED',
      walletStatus: 'PROVISIONED',
      cardStatus: 'ACTIVE',
      payrollAmount: Money.fromMajorString('45500.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('2600.00', Currency.usd),
      walletAddress: '0xseba...rtiz',
      cardId: 'card_demo_mxn_3300',
      cardLast4: '3300',
    ),
    EmployeeModel(
      id: 'emp_blessing_danjuma',
      bmoniUserId: 'usr_bmoni_blessing_ngn',
      firstName: 'Blessing',
      lastName: 'Danjuma',
      email: 'blessing.danjuma@example.ng',
      phoneNumber: '+2348067890123',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'PENDING',
      onboardingStatus: 'PENDING',
      walletStatus: 'PENDING',
      cardStatus: 'PENDING',
      payrollAmount: Money.fromMajorString('3410000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('2200.00', Currency.usd),
      walletAddress: null,
      cardId: null,
      cardLast4: '2299',
    ),
    EmployeeModel(
      id: 'emp_mariana_silva',
      bmoniUserId: 'usr_bmoni_mariana_mxn',
      firstName: 'Mariana',
      lastName: 'Silva',
      email: 'mariana.silva@example.mx',
      phoneNumber: '+525556789014',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'PENDING',
      onboardingStatus: 'PENDING',
      walletStatus: 'PENDING',
      cardStatus: 'PENDING',
      payrollAmount: Money.fromMajorString('59500.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('3400.00', Currency.usd),
      walletAddress: null,
      cardId: null,
      cardLast4: '1188',
    ),
    EmployeeModel(
      id: 'emp_chloe_gagnon',
      bmoniUserId: 'usr_bmoni_chloe_cad',
      firstName: 'Chloe',
      lastName: 'Gagnon',
      email: 'chloe.gagnon@example.ca',
      phoneNumber: '+13065550129',
      country: 'CA',
      countryName: 'Canada',
      targetCurrency: Currency.cad,
      status: 'PENDING',
      onboardingStatus: 'PENDING',
      walletStatus: 'PENDING',
      cardStatus: 'PENDING',
      payrollAmount: Money.fromMajorString('3712.50', Currency.cad),
      usdPayrollAmount: Money.fromMajorString('2700.00', Currency.usd),
      walletAddress: null,
      cardId: null,
      cardLast4: '9955',
    ),
    EmployeeModel(
      id: 'emp_tunde_salami',
      bmoniUserId: 'usr_bmoni_tunde_ngn',
      firstName: 'Tunde',
      lastName: 'Salami',
      email: 'tunde.salami@example.ng',
      phoneNumber: '+2348078901234',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'PENDING',
      onboardingStatus: 'PENDING',
      walletStatus: 'PENDING',
      cardStatus: 'PENDING',
      payrollAmount: Money.fromMajorString('4340000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('2800.00', Currency.usd),
      walletAddress: null,
      cardId: null,
      cardLast4: '8844',
    ),
    EmployeeModel(
      id: 'emp_gabriel_reyes',
      bmoniUserId: 'usr_bmoni_gabriel_mxn',
      firstName: 'Gabriel',
      lastName: 'Reyes',
      email: 'gabriel.reyes@example.mx',
      phoneNumber: '+525567890125',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'PENDING',
      onboardingStatus: 'PENDING',
      walletStatus: 'PENDING',
      cardStatus: 'PENDING',
      payrollAmount: Money.fromMajorString('43750.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('2500.00', Currency.usd),
      walletAddress: null,
      cardId: null,
      cardLast4: '7733',
    ),
    EmployeeModel(
      id: 'emp_halima_usman',
      bmoniUserId: 'usr_bmoni_halima_ngn',
      firstName: 'Halima',
      lastName: 'Usman',
      email: 'halima.usman@example.ng',
      phoneNumber: '+2348089012345',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'PENDING',
      onboardingStatus: 'PENDING',
      walletStatus: 'PENDING',
      cardStatus: 'PENDING',
      payrollAmount: Money.fromMajorString('3720000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('2400.00', Currency.usd),
      walletAddress: null,
      cardId: null,
      cardLast4: '6622',
    ),
    EmployeeModel(
      id: 'emp_jimena_castro',
      bmoniUserId: 'usr_bmoni_jimena_mxn',
      firstName: 'Jimena',
      lastName: 'Castro',
      email: 'jimena.castro@example.mx',
      phoneNumber: '+525578901236',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'PENDING',
      onboardingStatus: 'PENDING',
      walletStatus: 'PENDING',
      cardStatus: 'PENDING',
      payrollAmount: Money.fromMajorString('52500.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('3000.00', Currency.usd),
      walletAddress: null,
      cardId: null,
      cardLast4: '5511',
    ),
    EmployeeModel(
      id: 'emp_william_lavoie',
      bmoniUserId: 'usr_bmoni_william_cad',
      firstName: 'William',
      lastName: 'Lavoie',
      email: 'william.lavoie@example.ca',
      phoneNumber: '+17095550110',
      country: 'CA',
      countryName: 'Canada',
      targetCurrency: Currency.cad,
      status: 'INVITED',
      onboardingStatus: 'INVITED',
      walletStatus: 'PENDING',
      cardStatus: 'PENDING',
      payrollAmount: Money.fromMajorString('4812.50', Currency.cad),
      usdPayrollAmount: Money.fromMajorString('3500.00', Currency.usd),
      walletAddress: null,
      cardId: null,
      cardLast4: '4400',
    ),
    EmployeeModel(
      id: 'emp_obinna_nnamdi',
      bmoniUserId: 'usr_bmoni_obinna_ngn',
      firstName: 'Obinna',
      lastName: 'Nnamdi',
      email: 'obinna.nnamdi@example.ng',
      phoneNumber: '+2348090123456',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'INVITED',
      onboardingStatus: 'INVITED',
      walletStatus: 'PENDING',
      cardStatus: 'PENDING',
      payrollAmount: Money.fromMajorString('5115000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('3300.00', Currency.usd),
      walletAddress: null,
      cardId: null,
      cardLast4: '3399',
    ),
    EmployeeModel(
      id: 'emp_alejandro_mendoza',
      bmoniUserId: 'usr_bmoni_alejandro_mxn',
      firstName: 'Alejandro',
      lastName: 'Mendoza',
      email: 'alejandro.mendoza@example.mx',
      phoneNumber: '+525589012347',
      country: 'MX',
      countryName: 'Mexico',
      targetCurrency: Currency.mxn,
      status: 'INVITED',
      onboardingStatus: 'INVITED',
      walletStatus: 'PENDING',
      cardStatus: 'PENDING',
      payrollAmount: Money.fromMajorString('50750.00', Currency.mxn),
      usdPayrollAmount: Money.fromMajorString('2900.00', Currency.usd),
      walletAddress: null,
      cardId: null,
      cardLast4: '2288',
    ),
    EmployeeModel(
      id: 'emp_ronke_lawal',
      bmoniUserId: 'usr_bmoni_ronke_ngn',
      firstName: 'Ronke',
      lastName: 'Lawal',
      email: 'ronke.lawal@example.ng',
      phoneNumber: '+2348011223344',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'INVITED',
      onboardingStatus: 'INVITED',
      walletStatus: 'PENDING',
      cardStatus: 'PENDING',
      payrollAmount: Money.fromMajorString('4030000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('2600.00', Currency.usd),
      walletAddress: null,
      cardId: null,
      cardLast4: '1177',
    ),
    EmployeeModel(
      id: 'emp_segun_balogun',
      bmoniUserId: 'usr_bmoni_segun_ngn',
      firstName: 'Segun',
      lastName: 'Balogun',
      email: 'segun.balogun@example.ng',
      phoneNumber: '+2348022334455',
      country: 'NG',
      countryName: 'Nigeria',
      targetCurrency: Currency.ngn,
      status: 'INVITED',
      onboardingStatus: 'INVITED',
      walletStatus: 'PENDING',
      cardStatus: 'PENDING',
      payrollAmount: Money.fromMajorString('5270000.00', Currency.ngn),
      usdPayrollAmount: Money.fromMajorString('3400.00', Currency.usd),
      walletAddress: null,
      cardId: null,
      cardLast4: '9944',
    ),
  ];

  static final List<VirtualCardModel> cards = [
    VirtualCardModel(
      id: 'card_demo_usd_01',
      cardName: 'FlowPay Executive Card',
      cardColor: '#6366F1',
      currency: Currency.usd,
      status: 'active',
      last4: '5510',
      maskedPan: '•••• •••• •••• 5510',
      expirationDate: '08/29',
      monthlySpendLimit: Money.fromMajorString('5000.00', Currency.usd),
    ),
    VirtualCardModel(
      id: 'card_demo_ngn_01',
      cardName: 'Lagos Operations Card',
      cardColor: '#10B981',
      currency: Currency.ngn,
      status: 'active',
      last4: '8814',
      maskedPan: '•••• •••• •••• 8814',
      expirationDate: '11/28',
      monthlySpendLimit: Money.fromMajorString('1500000.00', Currency.ngn),
    ),
    VirtualCardModel(
      id: 'card_demo_mxn_02',
      cardName: 'Mexico City Card',
      cardColor: '#EC4899',
      currency: Currency.mxn,
      status: 'active',
      last4: '4289',
      maskedPan: '•••• •••• •••• 4289',
      expirationDate: '05/29',
      monthlySpendLimit: Money.fromMajorString('30000.00', Currency.mxn),
    ),
    VirtualCardModel(
      id: 'card_demo_cad_03',
      cardName: 'Toronto Engineering Card',
      cardColor: '#EF4444',
      currency: Currency.cad,
      status: 'active',
      last4: '9032',
      maskedPan: '•••• •••• •••• 9032',
      expirationDate: '02/30',
      monthlySpendLimit: Money.fromMajorString('4000.00', Currency.cad),
    ),
  ];

  static final List<CardTransactionModel> transactions = [
    CardTransactionModel(
      id: 'ctx_demo_01',
      cardId: 'card_demo_usd_01',
      amount: Money.fromMajorString('24.50', Currency.usd),
      merchantName: 'AWS Cloud Services',
      category: 'Software & Cloud',
      status: 'settled',
      timestamp: DateTime.now().subtract(const Duration(hours: 4)),
    ),
    CardTransactionModel(
      id: 'ctx_demo_02',
      cardId: 'card_demo_usd_01',
      amount: Money.fromMajorString('15.00', Currency.usd),
      merchantName: 'GitHub Copilot Enterprise',
      category: 'Developer Tools',
      status: 'settled',
      timestamp: DateTime.now().subtract(const Duration(hours: 28)),
    ),
    CardTransactionModel(
      id: 'ctx_demo_03',
      cardId: 'card_demo_ngn_01',
      amount: Money.fromMajorString('45000.00', Currency.ngn),
      merchantName: 'Coworking Space Victoria Island',
      category: 'Office Space',
      status: 'settled',
      timestamp: DateTime.now().subtract(const Duration(hours: 50)),
    ),
    CardTransactionModel(
      id: 'ctx_demo_04',
      cardId: 'card_demo_cad_03',
      amount: Money.fromMajorString('85.20', Currency.cad),
      merchantName: 'Shopify Plus Team Subscription',
      category: 'Software',
      status: 'settled',
      timestamp: DateTime.now().subtract(const Duration(hours: 12)),
    ),
  ];

  static PayrollRunModel getPayrollPreview() {
    final item1 = PayrollItemModel(
      employeeId: 'emp_bunch_dillon',
      employeeName: 'Bunch Dillon',
      country: 'NG',
      targetCurrency: Currency.ngn,
      destinationStablecoin: 'CNGN',
      targetAmount:
          Money.fromMajorString('3100000.00', Currency.ngn), // ₦3,100,000
      usdAmount: Money.fromMajorString('2000.00', Currency.usd), // $2,000
      exchangeRate: 1550.0,
      status: 'PENDING',
      isRailActive: true,
      railValidationMessage: 'CNGN Rail Active & Verified',
    );

    final item2 = PayrollItemModel(
      employeeId: 'emp_samson_jabo',
      employeeName: 'Samson Jabo',
      country: 'MX',
      targetCurrency: Currency.mxn,
      destinationStablecoin: 'MEXe',
      targetAmount:
          Money.fromMajorString('35000.00', Currency.mxn), // $35,000 MXN
      usdAmount: Money.fromMajorString('2000.00', Currency.usd), // $2,000
      exchangeRate: 17.5,
      status: 'PENDING',
      isRailActive: true,
      railValidationMessage: 'MEXe Rail Active & Verified',
    );

    return PayrollRunModel(
      runId: 'demo_run_preview',
      title: 'Global Engineering & Design Payroll',
      totalUsd: Money.fromMajorString('4000.00', Currency.usd),
      totalFeeUsd:
          Money.fromMajorString('10.00', Currency.usd), // $10 vs $340 wire fee
      totalSavedFeeUsd: Money.fromMajorString('330.00', Currency.usd),
      savedPercentage: 97.0,
      employerBalanceUsd: Money.fromMajorString('24500.00', Currency.usd),
      isBalanceSufficient: true,
      employeeCount: 2,
      countries: const ['NG', 'MX'],
      currencies: const ['NGN', 'MXN'],
      items: [item1, item2],
      status: 'PREVIEW',
      executedAt: DateTime.now(),
      isDemo: true,
    );
  }
}
