import '../../design_system/states.dart';
import '../../models/paginated_result.dart';
import '../../money/currency.dart';
import '../../money/money.dart';
import '../../repositories/activity_repository.dart';

/// In-memory Demo implementation of ActivityRepository
/// Seeded with 50 rich deterministic activities spanning transfers, missions,
/// conversions, cards, and failures to verify robust pagination across 5 pages.
class DemoActivityRepository implements ActivityRepository {
  final List<ActivityModel> _activities = [
    // 1. Pending Approvals
    ActivityModel(
      id: 'act_demo_01',
      title: 'Transfer to Designer in Ghana',
      description:
          'Transfer of \$500.00 USD awaiting on-device B-Key PIN approval',
      amount: Money.fromMajorString('500.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Kofi Mensah (Ghana)',
      status: FlowPayAppStatus.awaitingApproval,
      timestamp: DateTime.now().subtract(const Duration(minutes: 15)),
      reference: 'FP-TXN-884210',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Kofi Mensah (0x4A8...3b12)',
      fee: Money.fromMajorString('0.50', Currency.usd),
      exchangeRate: 'N/A (Direct Currency)',
      bmoniReference: 'prop_bmoni_0428',
      metadata: {
        'recipient': 'kofi.mensah@example.gh',
        'rail': 'USDB',
        'proposalId': 'prop_bmoni_0428'
      },
    ),
    ActivityModel(
      id: 'act_demo_02',
      title: 'Tax Reserve 20% Auto-Sweep',
      description: 'AI-interpreted mission rule awaiting user confirmation',
      amount: Money.fromMajorString('320.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.mission,
      category: ActivityCategory.mission,
      counterparty: 'Tax Reserve Vault (USDB)',
      status: FlowPayAppStatus.awaitingApproval,
      timestamp: DateTime.now().subtract(const Duration(minutes: 35)),
      reference: 'FP-MSN-991204',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Tax Reserve Smart Vault',
      fee: Money.fromMajorString('0.00', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: 'prop_mission_9912',
      metadata: {'rule': '20% Tax Reserve Auto-Sweep'},
    ),

    // 2. Mission Executions
    ActivityModel(
      id: 'act_demo_03',
      title: 'Emergency Fund Auto-Sweep',
      description: 'Mission rule executed: 10% auto-routed to savings reserve',
      amount: Money.fromMajorString('150.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.mission,
      category: ActivityCategory.mission,
      counterparty: 'High-Yield NGN Savings Vault',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(hours: 2)),
      reference: 'FP-SWEEP-9812',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Savings Vault (cNGN)',
      fee: Money.fromMajorString('0.00', Currency.usd),
      exchangeRate: '1 USD = 1,550.00 NGN',
      bmoniReference: '0x9923...auto_sweep',
      metadata: {'rule': 'Emergency Fund 10% Allocation'},
    ),

    // 3. Transfers
    ActivityModel(
      id: 'act_demo_04',
      title: 'Transfer to Bunch Dillon',
      description: 'Sent \$150.00 USD (settled via B-Key on-device signing)',
      amount: Money.fromMajorString('150.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Bunch Dillon (Nigeria)',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(hours: 4)),
      reference: 'FP-TXN-0428',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Bunch Dillon (0x71C...9a19)',
      fee: Money.fromMajorString('0.50', Currency.usd),
      exchangeRate: 'N/A (Direct Currency)',
      bmoniReference: '0x3a92b77...deterministic',
      metadata: {'recipient': 'bunch.dillon@example.ng', 'rail': 'USDB'},
    ),
    ActivityModel(
      id: 'act_demo_05',
      title: 'Transfer to Samson Jabo',
      description: 'Disbursement of \$1,200.00 USD equivalent in Mexican Pesos',
      amount: Money.fromMajorString('1200.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Samson Jabo (Mexico)',
      status: FlowPayAppStatus.processing,
      timestamp: DateTime.now().subtract(const Duration(hours: 6)),
      reference: 'FP-TXN-1192',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Samson Jabo SPEI CLABE',
      fee: Money.fromMajorString('1.20', Currency.usd),
      exchangeRate: '1 USD = 17.50 MXN',
      bmoniReference: 'prop_bmoni_1192',
      metadata: {'recipient': 'samson.jabo@example.mx', 'rail': 'MEXe'},
    ),
    ActivityModel(
      id: 'act_demo_06',
      title: 'Transfer to Liam Tremblay',
      description: 'Cross-border payment of \$450.00 CAD initiated',
      amount: Money.fromMajorString('450.00', Currency.cad),
      currency: Currency.cad,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Liam Tremblay (Canada)',
      status: FlowPayAppStatus.pending,
      timestamp: DateTime.now().subtract(const Duration(hours: 9)),
      reference: 'FP-TXN-6610',
      source: 'CADC Smart Wallet',
      destination: 'Liam Tremblay Interac Rail',
      fee: Money.fromMajorString('0.75', Currency.cad),
      exchangeRate: 'N/A (Direct CADC)',
      bmoniReference: 'prop_cad_6610',
      metadata: {'recipient': 'liam.tremblay@example.ca', 'rail': 'CADC'},
    ),

    // 4. Conversions (FX)
    ActivityModel(
      id: 'act_demo_07',
      title: 'Instant FX: USD → NGN',
      description: 'Converted \$500.00 USD to ₦775,000 NGN @ 1,550.00',
      amount: Money.fromMajorString('500.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.conversion,
      category: ActivityCategory.fx,
      counterparty: 'BMONI cNGN Liquidity Pool',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
      reference: 'FP-FX-3319',
      source: 'Personal USDB Wallet',
      destination: 'Personal CNGN Wallet',
      fee: Money.fromMajorString('0.05', Currency.usd),
      exchangeRate: '1 USD = 1,550.00 NGN',
      bmoniReference: '0x49ca...9102',
      metadata: {'source': 'USDB', 'target': 'CNGN', 'rate': '1550.00'},
    ),

    // 5. Card Transactions
    ActivityModel(
      id: 'act_demo_08',
      title: 'Virtual Card: AWS Cloud Services',
      description:
          'Card •••• 5510 authorized \$24.50 recurring cloud subscription',
      amount: Money.fromMajorString('24.50', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.card,
      category: ActivityCategory.card,
      counterparty: 'AWS EMEA S.a.r.l.',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 8)),
      reference: 'FP-CRD-8812',
      source: 'FlowPay Virtual Card (•••• 5510)',
      destination: 'AWS EMEA Merchant',
      fee: Money.fromMajorString('0.00', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: 'auth_card_8812',
      metadata: {'merchant': 'AWS EMEA', 'cardLast4': '5510'},
    ),
    ActivityModel(
      id: 'act_demo_09',
      title: 'Virtual Card: Hotel Pre-Authorization',
      description: 'Booking reservation hold cancelled and released',
      amount: Money.fromMajorString('180.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.card,
      category: ActivityCategory.card,
      counterparty: 'Hilton Worldwide',
      status: FlowPayAppStatus.cancelled,
      timestamp: DateTime.now().subtract(const Duration(days: 2)),
      reference: 'FP-CRD-0041',
      source: 'FlowPay Virtual Card (•••• 5510)',
      destination: 'Hilton Worldwide Hold',
      fee: Money.fromMajorString('0.00', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: 'void_crd_0041',
      metadata: {
        'merchant': 'Hilton Worldwide',
        'reason': 'Customer Cancellation'
      },
    ),

    // 6. Wallet Operations
    ActivityModel(
      id: 'act_demo_10',
      title: 'Smart Wallet Provisioning',
      description:
          'B-Key on-device keypair initialized and registered with BMONI',
      amount: Money.fromMajorString('0.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.wallet,
      category: ActivityCategory.system,
      counterparty: 'BMONI Embedded Rails',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 3)),
      reference: 'FP-WLT-0001',
      source: 'On-Device Secure Enclave (B-Key)',
      destination: 'BMONI Testnet Account Abstraction',
      fee: Money.fromMajorString('0.00', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x71C84517C3741Cd1f85D2F2c3e14B9245A009a19',
      metadata: {'enclave': 'Hardware Keystore / Secure Enclave'},
    ),

    // 7. Failures
    ActivityModel(
      id: 'act_demo_11',
      title: 'Contractor Card Cap Exceeded',
      description:
          'Transaction declined: Attempted \$650.00 spend exceeded \$500 monthly cap',
      amount: Money.fromMajorString('650.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.card,
      category: ActivityCategory.card,
      counterparty: 'Apple Store Regent Street',
      status: FlowPayAppStatus.failed,
      timestamp: DateTime.now().subtract(const Duration(days: 3, hours: 4)),
      reference: 'FP-CRD-DECL-901',
      source: 'FlowPay Contractor Card (•••• 9012)',
      destination: 'Apple Store POS',
      fee: Money.fromMajorString('0.00', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: 'decl_crd_9012_limit',
      metadata: {
        'reason': 'Monthly spend cap (\$500.00) exceeded',
        'merchant': 'Apple Store'
      },
    ),
    ActivityModel(
      id: 'act_demo_12',
      title: 'Transfer to Vendor Failed',
      description:
          'Transfer failed: Target routing account temporarily unreachable',
      amount: Money.fromMajorString('250.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Apex Global Logistics',
      status: FlowPayAppStatus.failed,
      timestamp: DateTime.now().subtract(const Duration(days: 4)),
      reference: 'FP-TXN-FAIL-302',
      source: 'Personal USDB Wallet',
      destination: 'Apex Global Account',
      fee: Money.fromMajorString('0.00', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: 'err_rail_unreachable',
      metadata: {
        'reason': 'Target rail network timeout',
        'recipient': 'Apex Global'
      },
    ),

    // 8. Extended Historical Activities (Deterministic Pagination Scale)
    ActivityModel(
      id: 'act_demo_13',
      title: 'Contractor Invoice Payment',
      description: 'Settled invoice via Polygon network',
      amount: Money.fromMajorString('850.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Tunde Bakare',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 5)),
      reference: 'FP-AUD-1013',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Tunde Bakare Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x2fd4b50fd0000000',
      metadata: {'counterparty': 'Tunde Bakare'},
    ),
    ActivityModel(
      id: 'act_demo_14',
      title: 'Instant FX: USD → MXN',
      description: 'Converted USD to MXN for supplier payout',
      amount: Money.fromMajorString('1400.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.conversion,
      category: ActivityCategory.fx,
      counterparty: 'BMONI Liquidity',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 7)),
      reference: 'FP-AUD-1014',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'BMONI Liquidity Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x33829b9ae0000000',
      metadata: {'counterparty': 'BMONI Liquidity'},
    ),
    ActivityModel(
      id: 'act_demo_15',
      title: 'Virtual Card: GitHub Copilot',
      description: 'Developer AI seat billed to corporate card',
      amount: Money.fromMajorString('19.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.card,
      category: ActivityCategory.card,
      counterparty: 'GitHub Inc',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 8)),
      reference: 'FP-AUD-1015',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'GitHub Inc Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x37308225f0000000',
      metadata: {'counterparty': 'GitHub Inc'},
    ),
    ActivityModel(
      id: 'act_demo_16',
      title: 'Tax Reserve 15% Auto-Sweep',
      description: 'Autonomous tax escrow reservation rule',
      amount: Money.fromMajorString('210.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.mission,
      category: ActivityCategory.mission,
      counterparty: 'Tax Escrow Vault',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 10)),
      reference: 'FP-AUD-1016',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Tax Escrow Vault Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x3ade68b100000000',
      metadata: {'counterparty': 'Tax Escrow Vault'},
    ),
    ActivityModel(
      id: 'act_demo_17',
      title: 'Smart Wallet Gas Top-Up',
      description: 'Gas abstraction sponsor sponsorship confirmed',
      amount: Money.fromMajorString('5.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.wallet,
      category: ActivityCategory.system,
      counterparty: 'BMONI Paymaster',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 11)),
      reference: 'FP-AUD-1017',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'BMONI Paymaster Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x3e8c4f3c10000000',
      metadata: {'counterparty': 'BMONI Paymaster'},
    ),
    ActivityModel(
      id: 'act_demo_18',
      title: 'Transfer to Adeyemi Alabi',
      description: 'Direct stablecoin disbursement',
      amount: Money.fromMajorString('1200.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Adeyemi Alabi',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 13)),
      reference: 'FP-AUD-1018',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Adeyemi Alabi Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x423a35c720000000',
      metadata: {'counterparty': 'Adeyemi Alabi'},
    ),
    ActivityModel(
      id: 'act_demo_19',
      title: 'Instant FX: EUR → USD',
      description: 'Euro conversion settlement',
      amount: Money.fromMajorString('950.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.conversion,
      category: ActivityCategory.fx,
      counterparty: 'Curve Pool',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 14)),
      reference: 'FP-AUD-1019',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Curve Pool Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x45e81c5230000000',
      metadata: {'counterparty': 'Curve Pool'},
    ),
    ActivityModel(
      id: 'act_demo_20',
      title: 'Virtual Card: DigitalOcean Droplets',
      description: 'Staging environment compute nodes',
      amount: Money.fromMajorString('84.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.card,
      category: ActivityCategory.card,
      counterparty: 'DigitalOcean LLC',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 16)),
      reference: 'FP-AUD-1020',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'DigitalOcean LLC Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x499602dd40000000',
      metadata: {'counterparty': 'DigitalOcean LLC'},
    ),
    ActivityModel(
      id: 'act_demo_21',
      title: 'Treasury Yield Sweep',
      description: 'Weekly yield sweep to high-interest vault',
      amount: Money.fromMajorString('340.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.mission,
      category: ActivityCategory.mission,
      counterparty: 'Yield Protocol',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 17)),
      reference: 'FP-AUD-1021',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Yield Protocol Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x4d43e96850000000',
      metadata: {'counterparty': 'Yield Protocol'},
    ),
    ActivityModel(
      id: 'act_demo_22',
      title: 'Transfer to Maria Gomez',
      description: 'SPEI disbursement in Guadalajara',
      amount: Money.fromMajorString('1800.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Maria Gomez',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 19)),
      reference: 'FP-AUD-1022',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Maria Gomez Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x50f1cff360000000',
      metadata: {'counterparty': 'Maria Gomez'},
    ),
    ActivityModel(
      id: 'act_demo_23',
      title: 'Virtual Card: Vercel Bandwidth',
      description: 'Serverless deployment hosting fees',
      amount: Money.fromMajorString('40.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.card,
      category: ActivityCategory.card,
      counterparty: 'Vercel Inc',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 20)),
      reference: 'FP-AUD-1023',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Vercel Inc Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x549fb67e70000000',
      metadata: {'counterparty': 'Vercel Inc'},
    ),
    ActivityModel(
      id: 'act_demo_24',
      title: 'Transfer to Chidi Nwachukwu',
      description: 'Monthly engineering stipend',
      amount: Money.fromMajorString('2200.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Chidi Nwachukwu',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 22)),
      reference: 'FP-AUD-1024',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Chidi Nwachukwu Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x584d9d0980000000',
      metadata: {'counterparty': 'Chidi Nwachukwu'},
    ),
    ActivityModel(
      id: 'act_demo_25',
      title: 'Instant FX: CAD → USD',
      description: 'Cross-currency balancing sweep',
      amount: Money.fromMajorString('1100.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.conversion,
      category: ActivityCategory.fx,
      counterparty: 'Circle FX Engine',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 23)),
      reference: 'FP-AUD-1025',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Circle FX Engine Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x5bfb839490000000',
      metadata: {'counterparty': 'Circle FX Engine'},
    ),
    ActivityModel(
      id: 'act_demo_26',
      title: 'Virtual Card: OpenAI Platform',
      description: 'Inference API usage for FlowPay Copilot',
      amount: Money.fromMajorString('312.40', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.card,
      category: ActivityCategory.card,
      counterparty: 'OpenAI LLC',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 25)),
      reference: 'FP-AUD-1026',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'OpenAI LLC Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x5fa96a1fa0000000',
      metadata: {'counterparty': 'OpenAI LLC'},
    ),
    ActivityModel(
      id: 'act_demo_27',
      title: 'Transfer to Carlos Morales',
      description: 'Monterrey consulting fee payout',
      amount: Money.fromMajorString('900.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Carlos Morales',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 26)),
      reference: 'FP-AUD-1027',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Carlos Morales Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x635750aab0000000',
      metadata: {'counterparty': 'Carlos Morales'},
    ),
    ActivityModel(
      id: 'act_demo_28',
      title: 'Transfer to Femi Balogun',
      description: 'Lagos UI/UX milestone 2 completion',
      amount: Money.fromMajorString('1500.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Femi Balogun',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 28)),
      reference: 'FP-AUD-1028',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Femi Balogun Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x67053735c0000000',
      metadata: {'counterparty': 'Femi Balogun'},
    ),
    ActivityModel(
      id: 'act_demo_29',
      title: 'Virtual Card: Loom Enterprise',
      description: 'Video screen recording software for team',
      amount: Money.fromMajorString('75.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.card,
      category: ActivityCategory.card,
      counterparty: 'Loom Inc',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 29)),
      reference: 'FP-AUD-1029',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Loom Inc Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x6ab31dc0d0000000',
      metadata: {'counterparty': 'Loom Inc'},
    ),
    ActivityModel(
      id: 'act_demo_30',
      title: 'Quarterly Surplus Auto-Sweep',
      description: 'Surplus revenue swept to contingency reserves',
      amount: Money.fromMajorString('4500.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.mission,
      category: ActivityCategory.mission,
      counterparty: 'Treasury Vault',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 31)),
      reference: 'FP-AUD-1030',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Treasury Vault Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x6e61044be0000000',
      metadata: {'counterparty': 'Treasury Vault'},
    ),
    ActivityModel(
      id: 'act_demo_31',
      title: 'Transfer to Fatima Sanusi',
      description: 'Direct deposit via NIP bridge',
      amount: Money.fromMajorString('1350.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Fatima Sanusi',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 32)),
      reference: 'FP-AUD-1031',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Fatima Sanusi Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x720eead6f0000000',
      metadata: {'counterparty': 'Fatima Sanusi'},
    ),
    ActivityModel(
      id: 'act_demo_32',
      title: 'Contractor Invoice Payment',
      description: 'Settled invoice via Polygon network',
      amount: Money.fromMajorString('850.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Tunde Bakare',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 34)),
      reference: 'FP-AUD-1032',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Tunde Bakare Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x75bcd16200000000',
      metadata: {'counterparty': 'Tunde Bakare'},
    ),
    ActivityModel(
      id: 'act_demo_33',
      title: 'Instant FX: USD → MXN',
      description: 'Converted USD to MXN for supplier payout',
      amount: Money.fromMajorString('1400.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.conversion,
      category: ActivityCategory.fx,
      counterparty: 'BMONI Liquidity',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 35)),
      reference: 'FP-AUD-1033',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'BMONI Liquidity Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x796ab7ed10000000',
      metadata: {'counterparty': 'BMONI Liquidity'},
    ),
    ActivityModel(
      id: 'act_demo_34',
      title: 'Virtual Card: GitHub Copilot',
      description: 'Developer AI seat billed to corporate card',
      amount: Money.fromMajorString('19.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.card,
      category: ActivityCategory.card,
      counterparty: 'GitHub Inc',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 37)),
      reference: 'FP-AUD-1034',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'GitHub Inc Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x7d189e7820000000',
      metadata: {'counterparty': 'GitHub Inc'},
    ),
    ActivityModel(
      id: 'act_demo_35',
      title: 'Tax Reserve 15% Auto-Sweep',
      description: 'Autonomous tax escrow reservation rule',
      amount: Money.fromMajorString('210.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.mission,
      category: ActivityCategory.mission,
      counterparty: 'Tax Escrow Vault',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 38)),
      reference: 'FP-AUD-1035',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Tax Escrow Vault Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x80c6850330000000',
      metadata: {'counterparty': 'Tax Escrow Vault'},
    ),
    ActivityModel(
      id: 'act_demo_36',
      title: 'Smart Wallet Gas Top-Up',
      description: 'Gas abstraction sponsor sponsorship confirmed',
      amount: Money.fromMajorString('5.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.wallet,
      category: ActivityCategory.system,
      counterparty: 'BMONI Paymaster',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 40)),
      reference: 'FP-AUD-1036',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'BMONI Paymaster Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x84746b8e40000000',
      metadata: {'counterparty': 'BMONI Paymaster'},
    ),
    ActivityModel(
      id: 'act_demo_37',
      title: 'Transfer to Adeyemi Alabi',
      description: 'Direct stablecoin disbursement',
      amount: Money.fromMajorString('1200.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Adeyemi Alabi',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 41)),
      reference: 'FP-AUD-1037',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Adeyemi Alabi Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x8822521950000000',
      metadata: {'counterparty': 'Adeyemi Alabi'},
    ),
    ActivityModel(
      id: 'act_demo_38',
      title: 'Instant FX: EUR → USD',
      description: 'Euro conversion settlement',
      amount: Money.fromMajorString('950.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.conversion,
      category: ActivityCategory.fx,
      counterparty: 'Curve Pool',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 43)),
      reference: 'FP-AUD-1038',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Curve Pool Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x8bd038a460000000',
      metadata: {'counterparty': 'Curve Pool'},
    ),
    ActivityModel(
      id: 'act_demo_39',
      title: 'Virtual Card: DigitalOcean Droplets',
      description: 'Staging environment compute nodes',
      amount: Money.fromMajorString('84.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.card,
      category: ActivityCategory.card,
      counterparty: 'DigitalOcean LLC',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 44)),
      reference: 'FP-AUD-1039',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'DigitalOcean LLC Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x8f7e1f2f70000000',
      metadata: {'counterparty': 'DigitalOcean LLC'},
    ),
    ActivityModel(
      id: 'act_demo_40',
      title: 'Treasury Yield Sweep',
      description: 'Weekly yield sweep to high-interest vault',
      amount: Money.fromMajorString('340.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.mission,
      category: ActivityCategory.mission,
      counterparty: 'Yield Protocol',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 46)),
      reference: 'FP-AUD-1040',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Yield Protocol Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x932c05ba80000000',
      metadata: {'counterparty': 'Yield Protocol'},
    ),
    ActivityModel(
      id: 'act_demo_41',
      title: 'Transfer to Maria Gomez',
      description: 'SPEI disbursement in Guadalajara',
      amount: Money.fromMajorString('1800.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Maria Gomez',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 47)),
      reference: 'FP-AUD-1041',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Maria Gomez Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x96d9ec4590000000',
      metadata: {'counterparty': 'Maria Gomez'},
    ),
    ActivityModel(
      id: 'act_demo_42',
      title: 'Virtual Card: Vercel Bandwidth',
      description: 'Serverless deployment hosting fees',
      amount: Money.fromMajorString('40.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.card,
      category: ActivityCategory.card,
      counterparty: 'Vercel Inc',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 49)),
      reference: 'FP-AUD-1042',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Vercel Inc Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x9a87d2d0a0000000',
      metadata: {'counterparty': 'Vercel Inc'},
    ),
    ActivityModel(
      id: 'act_demo_43',
      title: 'Transfer to Chidi Nwachukwu',
      description: 'Monthly engineering stipend',
      amount: Money.fromMajorString('2200.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Chidi Nwachukwu',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 50)),
      reference: 'FP-AUD-1043',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Chidi Nwachukwu Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0x9e35b95bb0000000',
      metadata: {'counterparty': 'Chidi Nwachukwu'},
    ),
    ActivityModel(
      id: 'act_demo_44',
      title: 'Instant FX: CAD → USD',
      description: 'Cross-currency balancing sweep',
      amount: Money.fromMajorString('1100.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.conversion,
      category: ActivityCategory.fx,
      counterparty: 'Circle FX Engine',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 52)),
      reference: 'FP-AUD-1044',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Circle FX Engine Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0xa1e39fe6c0000000',
      metadata: {'counterparty': 'Circle FX Engine'},
    ),
    ActivityModel(
      id: 'act_demo_45',
      title: 'Virtual Card: OpenAI Platform',
      description: 'Inference API usage for FlowPay Copilot',
      amount: Money.fromMajorString('312.40', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.card,
      category: ActivityCategory.card,
      counterparty: 'OpenAI LLC',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 53)),
      reference: 'FP-AUD-1045',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'OpenAI LLC Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0xa5918671d0000000',
      metadata: {'counterparty': 'OpenAI LLC'},
    ),
    ActivityModel(
      id: 'act_demo_46',
      title: 'Transfer to Carlos Morales',
      description: 'Monterrey consulting fee payout',
      amount: Money.fromMajorString('900.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Carlos Morales',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 55)),
      reference: 'FP-AUD-1046',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Carlos Morales Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0xa93f6cfce0000000',
      metadata: {'counterparty': 'Carlos Morales'},
    ),
    ActivityModel(
      id: 'act_demo_47',
      title: 'Transfer to Femi Balogun',
      description: 'Lagos UI/UX milestone 2 completion',
      amount: Money.fromMajorString('1500.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Femi Balogun',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 56)),
      reference: 'FP-AUD-1047',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Femi Balogun Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0xaced5387f0000000',
      metadata: {'counterparty': 'Femi Balogun'},
    ),
    ActivityModel(
      id: 'act_demo_48',
      title: 'Virtual Card: Loom Enterprise',
      description: 'Video screen recording software for team',
      amount: Money.fromMajorString('75.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.card,
      category: ActivityCategory.card,
      counterparty: 'Loom Inc',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 58)),
      reference: 'FP-AUD-1048',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Loom Inc Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0xb09b3a1300000000',
      metadata: {'counterparty': 'Loom Inc'},
    ),
    ActivityModel(
      id: 'act_demo_49',
      title: 'Quarterly Surplus Auto-Sweep',
      description: 'Surplus revenue swept to contingency reserves',
      amount: Money.fromMajorString('4500.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.mission,
      category: ActivityCategory.mission,
      counterparty: 'Treasury Vault',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 59)),
      reference: 'FP-AUD-1049',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Treasury Vault Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0xb449209e10000000',
      metadata: {'counterparty': 'Treasury Vault'},
    ),
    ActivityModel(
      id: 'act_demo_50',
      title: 'Transfer to Fatima Sanusi',
      description: 'Direct deposit via NIP bridge',
      amount: Money.fromMajorString('1350.00', Currency.usd),
      currency: Currency.usd,
      type: ActivityType.transfer,
      category: ActivityCategory.transfer,
      counterparty: 'Fatima Sanusi',
      status: FlowPayAppStatus.completed,
      timestamp: DateTime.now().subtract(const Duration(days: 61)),
      reference: 'FP-AUD-1050',
      source: 'Personal Smart Wallet (USDB)',
      destination: 'Fatima Sanusi Account',
      fee: Money.fromMajorString('0.10', Currency.usd),
      exchangeRate: 'N/A',
      bmoniReference: '0xb7f7072920000000',
      metadata: {'counterparty': 'Fatima Sanusi'},
    ),
  ];

  @override
  Future<List<ActivityModel>> getRecentActivities({
    int limit = 50,
    ActivityCategory? category,
    ActivityType? type,
  }) async {
    var list = _activities;
    if (type != null) {
      list = list.where((a) => a.type == type).toList();
    } else if (category != null) {
      list = list.where((a) => a.category == category).toList();
    }
    return list.take(limit).toList();
  }

  Future<PaginatedResult<ActivityModel>> getPaginatedActivities({
    int page = 1,
    int limit = 10,
    ActivityCategory? category,
    ActivityType? type,
    String? searchQuery,
  }) async {
    var list = _activities;
    if (type != null) {
      list = list.where((a) => a.type == type).toList();
    } else if (category != null) {
      list = list.where((a) => a.category == category).toList();
    }

    if (searchQuery != null && searchQuery.trim().isNotEmpty) {
      final q = searchQuery.toLowerCase().trim();
      list = list.where((a) {
        return a.title.toLowerCase().contains(q) ||
            a.description.toLowerCase().contains(q) ||
            a.counterparty.toLowerCase().contains(q) ||
            a.reference.toLowerCase().contains(q);
      }).toList();
    }

    return PaginatedResult.paginateList(list, page: page, limit: limit);
  }

  @override
  Future<ActivityModel> recordActivity(ActivityModel activity) async {
    final idx = _activities.indexWhere(
      (a) =>
          a.id == activity.id ||
          (a.reference.isNotEmpty && a.reference == activity.reference),
    );
    if (idx != -1) {
      _activities[idx] = activity;
    } else {
      _activities.insert(0, activity);
    }
    return activity;
  }
}
