import '../../money/currency.dart';
import '../../money/money.dart';

enum PlannedActionType {
  send,
  reserve,
  allocate,
  convert,
  createMission,
  billPay;

  String get displayName {
    switch (this) {
      case PlannedActionType.send:
        return 'Send';
      case PlannedActionType.reserve:
        return 'Reserve';
      case PlannedActionType.allocate:
        return 'Allocate';
      case PlannedActionType.convert:
        return 'Convert';
      case PlannedActionType.createMission:
        return 'Set Rule';
      case PlannedActionType.billPay:
        return 'Pay Bill';
    }
  }
}

/// Balance Impact line item showing before/after projections per wallet
class BalanceImpact {
  final String walletId;
  final String walletName;
  final Currency currency;
  final Money currentBalance;
  final Money projectedBalance;
  final Money delta; // Negative for debit, positive for credit

  const BalanceImpact({
    required this.walletId,
    required this.walletName,
    required this.currency,
    required this.currentBalance,
    required this.projectedBalance,
    required this.delta,
  });

  bool get isDebit => delta.minorUnits < 0;
  bool get isCredit => delta.minorUnits > 0;
}

/// Deterministic validation output
class PlanValidationResult {
  final bool isValid;
  final List<String> errors;
  final List<String> warnings;

  const PlanValidationResult({
    required this.isValid,
    this.errors = const [],
    this.warnings = const [],
  });

  factory PlanValidationResult.valid({List<String> warnings = const []}) {
    return PlanValidationResult(isValid: true, warnings: warnings);
  }

  factory PlanValidationResult.invalid(List<String> errors,
      {List<String> warnings = const []}) {
    return PlanValidationResult(
        isValid: false, errors: errors, warnings: warnings);
  }
}

/// A line item in the financial plan
class PlannedFinancialAction {
  final String id;
  final PlannedActionType type;
  final Money amount;
  final String? percentageLabel;
  final String sourceWalletId;
  final String sourceWalletName;
  final String destinationId;
  final String destinationName;
  final String destinationType; // 'beneficiary', 'reserve', 'wallet'
  final String description;
  final String? fxRate;
  final Money fee;

  const PlannedFinancialAction({
    required this.id,
    required this.type,
    required this.amount,
    this.percentageLabel,
    required this.sourceWalletId,
    required this.sourceWalletName,
    required this.destinationId,
    required this.destinationName,
    required this.destinationType,
    required this.description,
    this.fxRate,
    required this.fee,
  });
}

/// Structured Financial Plan
/// Immutable specification generated by the Financial Planner and passed to the
/// Policy Validator and User Review before execution authorization.
class FinancialPlan {
  final String planId;
  final String title;
  final String summary;
  final List<PlannedFinancialAction> actions;
  final Money totalDebit;
  final Money totalFee;
  final List<BalanceImpact> expectedBalanceChanges;
  final PlanValidationResult validation;
  final bool isApproved;
  final DateTime createdAt;
  final String executionState; // DRAFT, READY_FOR_REVIEW, APPROVED, EXECUTING, COMPLETED, FAILED
  final String? txHash;

  const FinancialPlan({
    required this.planId,
    required this.title,
    required this.summary,
    required this.actions,
    required this.totalDebit,
    required this.totalFee,
    required this.expectedBalanceChanges,
    required this.validation,
    this.isApproved = false,
    required this.createdAt,
    this.executionState = 'READY_FOR_REVIEW',
    this.txHash,
  });

  FinancialPlan copyWith({
    String? planId,
    String? title,
    String? summary,
    List<PlannedFinancialAction>? actions,
    Money? totalDebit,
    Money? totalFee,
    List<BalanceImpact>? expectedBalanceChanges,
    PlanValidationResult? validation,
    bool? isApproved,
    DateTime? createdAt,
    String? executionState,
    String? txHash,
  }) {
    return FinancialPlan(
      planId: planId ?? this.planId,
      title: title ?? this.title,
      summary: summary ?? this.summary,
      actions: actions ?? this.actions,
      totalDebit: totalDebit ?? this.totalDebit,
      totalFee: totalFee ?? this.totalFee,
      expectedBalanceChanges:
          expectedBalanceChanges ?? this.expectedBalanceChanges,
      validation: validation ?? this.validation,
      isApproved: isApproved ?? this.isApproved,
      createdAt: createdAt ?? this.createdAt,
      executionState: executionState ?? this.executionState,
      txHash: txHash ?? this.txHash,
    );
  }
}
